algoritmo "Exemplo Vetor"
// Função :
// Autor :
// Data : 16/04/2025
// Seção de Declarações 
var

 nome_aluno: vetor [1..30] de literal
 contador: inteiro

inicio

para contador de 1 ate 3 faca
     escreval ("Informe o nome do aluno: ")
     leia(nome_aluno[contador])
fimpara

para contador de 1 ate 3 faca
     escreval ("O nome é: ", nome_aluno [contador])
fimpara

fimalgoritmo
