algoritmo "Teste do SE"
// Função :
// Autor :
// Data : 26/03/2025
// Seção de Declarações 
var

   mediaFinal: inteiro

inicio

   mediaFinal <-5 // ou mediaFinal:=6
   
   se mediaFinal >= 6 entao
      escreval ("Aluno Aprovado!!!")
  senao
       escreval ("Aluno Reprovado!!")
   fimse
   

                 // IDENTAÇÃO: serve pra facilitar a visualização do algoritmo
fimalgoritmo
